name: "Continous Integration For PowerBI"

on:

    pull_request:

        branches:

            - main
            - sandbox

        paths-ignore:
            - 'src/**'
            - '.github/**'
            - 'pyproject.toml'
            - 'README.md'


permissions:
  contents: read

jobs:

    scope:

        uses: ./.github/workflows/scope.yaml
        with:
            base_ref: origin/${{ github.base_ref }}
       

    echo-scope:
        runs-on: ubuntu-latest
        needs: scope
        steps:
            - name: Printing GITHUB_OUTPUT
              run: |
                echo "workspace = ${{needs.scope.outputs.workspace}}"
                echo "has_changes = ${{needs.scope.outputs.has_changes}}"
                echo "semantic_models = ${{needs.scope.outputs.semantic_models}}"
                echo "reports = ${{needs.scope.outputs.reports}}"





